### ISSUE TITLE
Change default port to 8013

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#118]
The default port needs to be changed to a less common port. According [wikipedia](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers), 8013 is not current registered in IANA.
- [x] open-feature/flagd#119
- [x] open-feature/open-feature-operator#65
- [x] open-feature/node-sdk-contrib#82
- [x] open-feature/golang-sdk-contrib#7
