### ISSUE TITLE
[FEATURE] Chainable if/then else if/then else

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#1263]
### Requirements

JsonLogic supports chainable if/then else if/then logic. This can simplify how complex conditionals can be represented in a targeting rule. It should be supported by all [spec-compliant JsonLogic implementations](https://jsonlogic.com/operations.html#if).

```[tasklist]
### Tasks
- [ ] https://github.com/open-feature/flagd-schemas/issues/137
- [x] Update the flagd documentation to include examples of an else if condition
- [x] Update the playground examples to no longer use nested if conditions.
```

This is a follow-up to [this issue](https://github.com/open-feature/flagd/issues/1258).
