### ISSUE TITLE
[FEATURE] Specify custom seed for fractional operator

### ISSUE THREAD

**Issue by colebaileygit** [open-feature/flagd#1264]
### Requirements

Currently, the `fractional` implementation defaults to using `$flagd.flagKey` as prefix for the hash key to seed the hash. This is a good default for running independent experiments across multiple feature flags at the same time.

We would also like to be able to correlate multiple feature flags / systems to a single experiment, meaning the same user should be allocated to the same variant group across multiple flags and hence the same seed must be used. For this reason we would not want to use flagKey as a seed, but some unique experimentId injected into the flag targeting.

My proposal to make this possible while keeping backwards compatibility would be to allow an optional custom seed as second argument to `fractional`, e.g.:

```javascript
// Custom static seed
"targeting": {
  "fractional": [
    { "var": "user.name" },
    "experiment-123",
    [ "clubs", 25 ],
    [ "diamonds", 25 ],
    [ "hearts", 25 ],
    [ "spades", 25 ]
  ]
}

// Custom seed from context
"targeting": {
  "fractional": [
    { "var": "user.name" },
    { "var": "populationSeed" },
    [ "clubs", 25 ],
    [ "diamonds", 25 ],
    [ "hearts", 25 ],
    [ "spades", 25 ]
  ]
}

// Status quo: custom key with default flagKey seed
"targeting": {
  "fractional": [
    { "var": "user.name" },
    [ "clubs", 25 ],
    [ "diamonds", 25 ],
    [ "hearts", 25 ],
    [ "spades", 25 ]
  ]
}

// Status quo: default targetingKey with default flagKey seed
"targeting": {
  "fractional": [
    [ "clubs", 25 ],
    [ "diamonds", 25 ],
    [ "hearts", 25 ],
    [ "spades", 25 ]
  ]
}
```

One downside to using positional arguments like this is there would be no way to provide a custom seed but also use the default `targetingKey` since the 1st argument will be interpreted as a hash key. However this has the simple workaround of explicitly giving the default value:

```javascript
// default targetingKey with custom seed
"targeting": {
  "fractional": [
    { "var": "targetingKey" },
    "experiment-123",
    [ "clubs", 25 ],
    [ "diamonds", 25 ],
    [ "hearts", 25 ],
    [ "spades", 25 ]
  ]
}
```
```[tasklist]
### Tasks
- [ ] https://github.com/open-feature/flagd/pull/1266
- [ ] https://github.com/open-feature/flagd-schemas/pull/136
- [ ] https://github.com/open-feature/flagd-testbed/pull/115
- [ ] https://github.com/open-feature/java-sdk-contrib/pull/737
- [ ] https://github.com/open-feature/python-sdk-contrib/pull/74
- [ ] https://github.com/open-feature/js-sdk-contrib/pull/870
```

**Comment by colebaileygit** [comment]
I took a stab at making this possible in flagd core -- see reference PRs above

This would also require implementing same behavior in each language's in-memory provider which should be pretty straightforward.

**Comment by toddbaert** [comment]
This sounds like a reasonable idea, and I appreciate your pr! I'll give it a proper look tomorrow.

**Comment by beeme1mr** [comment]
Hey @colebaileygit, this is great. We had discussions about this in the past and I actually thought it was already possible 😅. Our idea back in the day was basically the same as what you're proposing. If @toddbaert agrees, perhaps we start by updating flagd and the in-process implementations before updating the schema and docs.

**Comment by toddbaert** [comment]
@colebaileygit

I think you've highlighted a legitimate use-case and an existing shortcoming in flagd. Your proposal also seems solid to me.

That said, I'd like to propose something similar that will, perhaps, afford a better user-experience in the end...

## Proposal

Instead of adding a second optional arg as you've proposed, what if we change the existing implementation so that it does NOT automatically append the flag key. Essentially, [this line](https://github.com/open-feature/flagd/blob/2a185fdaa4722e1977a440c6cc847d8bc9fcff6e/core/pkg/evaluator/fractional.go#L70) would change to simply `return bucketBy, feDistributions, nil`. This would mean that users would now _fully_ control the "seed". If they wanted to use a seed they would have to implement it in their bucking expression.

This would require no schema changes, and I _think_ be a better user experience.

## Downsides

Of course, this would be a _behaviorally_ breaking change... however, we are still sub 1.0, and I really doubt many people are counting on this exact behavior anyway. Additionally, we could publish some very obvious guidance for how to work around the behavioral change to restore the previous behavior (simply append the flag-key to your bucketing value).

Also, we'd want to implement this in the in-process providers within a relatively short time frame to maintain behavioral parity.

What do you think? 

cc @beeme1mr

**Comment by colebaileygit** [comment]
In that case, the example configurations would look like this then?
```javascript
"targeting": {
  "fractional": [
    { "cat": ["experiment-123", { "var": "user.name" }] },
    [ "clubs", 25 ],
    [ "diamonds", 25 ],
    [ "hearts", 25 ],
    [ "spades", 25 ]
  ]
}

"targeting": {
  "fractional": [
    { "cat": [{ "var": "populationSeed": }, { "var": "user.name" }] },
    [ "clubs", 25 ],
    [ "diamonds", 25 ],
    [ "hearts", 25 ],
    [ "spades", 25 ]
  ]
}
```

This was actually my first attempt at getting this to work, so that does seem more intuitive and less restrictive since any nested jsonlogic could be used here including nested ifs etc (assuming we also resolve https://github.com/open-feature/flagd/issues/1265). I could imagine wild scenarios where you end up duplicating if statements twice if you for some reason want both the seed and key to be dynamic within a fractional invocation using my proposal, but I'd hope those are not the norm. I like this approach too 👍 

One downside is the "base" case becomes more verbose with `{ "cat": [{ "var": "$flagd.flagKey" }, { "var": "targetingKey" }] }` but given the shorthand op fills both in for you that should be fine and ensures there are no hidden variables. I wonder though if allowing "seedless" randomisations could become a foot-gun if people naively put in `{ "var": "user.email" }` like the docs indicate now since it is a good practice to ensure each flag is randomised independently from each other statistically speaking.

**Comment by toddbaert** [comment]
@colebaileygit @beeme1mr If you both agree, I think I'm comfortable suggesting that we go ahead with this implementation. @colebaileygit  would you be interested in getting started on that approach? You might have issues with the e2e suite expectations not matching the new behavior, but I can help you with that if you get stuck there.

**Comment by colebaileygit** [comment]
Sure thing! Will update the PRs above to the new approach and then look into the other memory providers that I know of

**Comment by Kavindu-Dodan** [comment]
+1 from my end. I also think this to be a good UX improvement.

**Comment by colebaileygit** [comment]
I've updated the linked PRs above, but wasn't able to quickly onboard the build / test process for `js-sdk-contrib` or the e2e suite for `java-sdk-contrib`, maybe someone more familiar would be faster there. Also I think we'll need to update the go-sdk once the new go-core version is available.

What's the order of operations to get all the PRs in sync with each other and versioned? Schemas > testbed > core > providers? I especially want to make sure I'm not messing anything up with the submodules and fork branches

**Comment by beeme1mr** [comment]
I'll try and knock out the `js-sdk-contrib` update. Perhaps @toddbaert or @Kavindu-Dodan could handle Java when they have a moment.

**Comment by Kavindu-Dodan** [comment]
> What's the order of operations to get all the PRs in sync with each other and versioned? Schemas > testbed > core > providers?

 Given there's a breaking change (test incompatibility), you could follow this order 
 
 flagd-testbed (updated tests) + new release -> flagd + new release 

flagd go provider should wait for flagd release as it uses the core module. The java provider can be updated independently as soon as flagd-testbed is ready with updated tests.

**Comment by colebaileygit** [comment]
Java PR is ready for review: https://github.com/open-feature/java-sdk-contrib/pull/737

Small issue still needs to be resolved with the test-harness since the RPC evaluator needs to be updated once the flagd release is ready. I could also imagine moving the docker-compose helper I added out of java repo and into test-harness might make more sense here, but maybe others have a better approach.

**Comment by beeme1mr** [comment]
@colebaileygit Updates the JS can be tracked [here](https://github.com/open-feature/js-sdk-contrib/pull/870).

**Comment by toddbaert** [comment]
@colebaileygit @beeme1mr I think this cane be closed with the merge of the JS implementation? Or is there something else we need as well?
