### ISSUE TITLE
Add support for flag metadata

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#1440]
## Overview

The OpenFeature specification includes a concept called [flag metadata](https://openfeature.dev/specification/types#flag-metadata). This is a great way to provide additional context in a flag evaluation. It's especially useful for troubleshooting and telemetry use cases.

## Requirements

```[tasklist]
### Tasks
- [ ] https://github.com/open-feature/flagd-schemas/issues/174
- [ ] https://github.com/open-feature/flagd/issues/1467
- [ ] https://github.com/open-feature/flagd/issues/1464
- [ ] https://github.com/open-feature/flagd/issues/1465
- [ ] https://github.com/open-feature/flagd/issues/1466
```

## Follow-up

Metadata at the flag set level would be useful for metadata that's shared across all flags (e.g. flag set version). This may require changes to the OpenFeature spec and SDKs to properly support.
