### ISSUE TITLE
[FEATURE] Improve evaluation performance

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#1453]
## Overview

The flag evaluation engine in flagd leverages JsonLogic to provide a powerful and flexible rule-based serializable logic. The flagd binary and in-process Go flagd provider use [this library](https://github.com/diegoholiveira/jsonlogic/issues/88). To improve flag evaluation performance and reduce computational overhead, the ruleset should be pre-decoded when a flag set is loaded (or updated). This removes the need to parse the JsonLogic structure for each evaluation.

```[tasklist]
### Tasks
- [ ] [Add support for pre-decoded rules in the Go JsonLogic SDK](https://github.com/diegoholiveira/jsonlogic/issues/88).
- [ ] Update flagd to use the pre-decoded rules.
- [ ] 🥇 Bonus points for running a performance test to measure the improvements
``` 

> This should be a non-breaking change in the Go JsonLogic SDK.

**Comment by aasifkhan7** [comment]
I'd like to work on this one @beeme1mr  ! Could you please assign it to me?

**Comment by aasifkhan7** [comment]
@beeme1mr To confirm, should this change be made in the repository at https://github.com/diegoholiveira/jsonlogic?

**Comment by toddbaert** [comment]
> [@beeme1mr](https://github.com/beeme1mr) To confirm, should this change be made in the repository at https://github.com/diegoholiveira/jsonlogic?

No, what @beeme1mr was getting at is that we parse and compile the JSON rules every time we evaluate ([here](https://github.com/open-feature/flagd/blob/0b11c6cf612b244bda6bab119814647f3ce8de2e/core/pkg/evaluator/json.go#L339)). We can instead only do this when the rules are first retrieved.

@beeme1mr please correct if I'm wrong

Assigning you, @aasifkhan7

**Comment by beeme1mr** [comment]
@aasifkhan7 is correct that the JSON Logic implementation in Go must be updated to support this feature first. Once that's in place, we need to update flagd to leverage it.

**Comment by aasifkhan7** [comment]
@beeme1mr @toddbaert Should it be the responsibility of the `jsonlogic` library to cache and store the decoded rule for subsequent evaluations? Or should the responsibility for caching and storing the decoded rule lie with the third-party application, such as `flagd`? 

What are your thoughts on the best approach for handling this?

**Comment by beeme1mr** [comment]
Hey @aasifkhan7, I propose that the JSON Logic library support a built step similar to what you see [here](https://json-logic.github.io/json-logic-engine/docs/). This would allow you to "hydrate" the JSON Logic engine during initiation instead of at evaluation time.

**Comment by aasifkhan7** [comment]
Hey @beeme1mr, based on [this comment](https://github.com/diegoholiveira/jsonlogic/pull/93#issuecomment-2568195546), it seems we’re expected to handle caching of all predecoded rules on our side. Does that approach work for you?
